add support for locks (mutual exclusion)

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -124,7 +124,7 @@ process_action_args() (
         echoh 'E4: no URL provided'; return 1
     fi &&
 
-    init_runtime g c p f &&
+    init_runtime g c p l f &&
     for url_arg in "$@"; do
         perform_action "$action" "$url_arg" || return
     done
@@ -141,7 +141,7 @@ echoh() {
 #-------------------------------------------------------------------------------
 
 run_list() (
-    init_runtime g c p f &&
+    init_runtime g c p l f &&
     db="$(get_db "$STATUS_PATH")" &&
     echon "$db" | while IFS= read -r record; do
         url="$(status_record_url "$record")" &&
@@ -152,7 +152,7 @@ run_list() (
 )
 
 run_clean() (
-    init_runtime c p &&
+    init_runtime c p l &&
     if ! remove_dir "$CACHE_DIR"; then
         echo 'E5: failed to remove cache directory' >&2; return 1
     fi
@@ -161,7 +161,8 @@ run_clean() (
 run_paths() (
     init_runtime c p &&
     echo "state-dir $STATE_DIR" &&
-    echo "cache-dir $CACHE_DIR"
+    echo "cache-dir $CACHE_DIR" &&
+    echo "lock-path $LOCK_PATH"
 )
 
 # $@ - echo arguments
@@ -223,6 +224,7 @@ init_runtime() {
             g) check_git ;;
             c) init_runtime_constants ;;
             p) init_paths ;;
+            l) init_lock ;;
             f) init_files ;;
             *) echo "E15: invalid runtime init flag $_flag" >&2; return 1 ;;
         esac || return
@@ -236,8 +238,10 @@ check_git() {
 }
 
 init_runtime_constants() {
-    _user_id="$(id -u)" &&
-    if [ "$_user_id" -eq 0 ]; then
+    UID="$(id -u)" &&
+    readonly UID &&
+
+    if [ "$UID" -eq 0 ]; then
         readonly ACCESS=global
     else
         readonly ACCESS=local
@@ -255,16 +259,41 @@ init_paths() {
         readonly STATE_DIR="$HOME"/.local/share/gitpack
         readonly CACHE_DIR="$HOME"/.cache/gitpack
     fi
+    readonly LOCK_DIR=/var/lock # unified storage of locks
 
     readonly STATUS_PATH="$STATE_DIR"/status # database of installed packages
     readonly REPOS_DIR="$CACHE_DIR"/repos # cache for local repositories
     readonly FETCHED_PATH="$CACHE_DIR"/fetched # repositories fetch timestamps
+    readonly LOCK_PATH="$LOCK_DIR"/gitpack-"$UID" # lock itself is a directory
+    readonly LOCK_PID_PATH="$LOCK_PATH"/pid # process ID of the lock holder
+}
+
+init_lock() {
+    mkdir -p "$LOCK_DIR"/ && # first create a directory for locks
+
+    if mkdir "$LOCK_PATH"/ 2>/dev/null; then # try to lock
+        trap exit_action EXIT && # function to call on an exit
+        trap exit HUP INT QUIT TERM && # call exit on these signals
+        echo "$$" > "$LOCK_PID_PATH"
+    else
+        _lockfile="$(basename "$LOCK_PATH")"
+        _pid="$(cat "$LOCK_PID_PATH")" # may not exist yet, not a problem though
+        echo "E17: lockfile $_lockfile is owned by process $_pid" >&2
+        return 1
+    fi
 }
 
 init_files() {
     init_db "$STATUS_PATH" &&
     init_db "$FETCHED_PATH"
 }
+
+exit_action() (
+    status="$?" # store exit status of last executed command
+    rm -f "$LOCK_PID_PATH"
+    rmdir "$LOCK_PATH"/
+    return "$status"
+)
 
 #-------------------------------------------------------------------------------
 # ACTION PROCESSING
