repo_cd check if URL is really provided

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -399,6 +399,10 @@ get_repo_hash() (
 # $1 - URL
 # $2 - hash (optional)
 repo_cd() {
+    if ! [ "$1" ]; then # just for sure
+        echo 'E18: cannot change directory to an empty URL' >&2; return 1
+    fi
+
     cd "$(url_to_path "$1")"/ &&
     if [ "$2" ]; then
         git checkout -qf "$2"
