Remove custom script timeout

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -33,7 +33,7 @@ main() {
 check_sw_deps() {
     # a list of required software
     sw_deps='command echo [ cd test pwd rm id mkdir touch grep git ls uname read
-             cp head cut true basename find rmdir tr date tail kill sleep wait'
+             cp head cut true basename find rmdir tr date tail kill'
 
     # check if any piece of software is missing
     for sw_dep in $sw_deps; do
@@ -103,9 +103,6 @@ init_constants() {
     LOGTYPE_PRERM=prerm # prerm script execution
     LOGTYPE_RM=rm # remove files using map
     LOGTYPE_POSTRM=postrm # postrm script execution
-
-    # other constants
-    SIGCHLD_EXIT_STATUS=145 # SIGCHLD number is 17, signals exit with 128+n
 }
 
 # DESCRIPTION:
@@ -145,7 +142,6 @@ init_configuration() {
     COMMAND="$0 $*" # the complete current GitPack command
 
     LOG_LINES_KEPT=1000 # when shortening the log file, keep those last lines
-    SCRIPT_TIMEOUT=900 # timeout in seconds used when calling custom scripts
     MAX_DEP_DEPTH=20 # max depth of dependencies, prevent cyclic dependencies
 }
 
@@ -794,56 +790,17 @@ install_method_to_path() {
     echo .gitpack/install/"$1"
 }
 
-#-------------------------------------------------------------------------------
-# CONTROL SCRIPT EXECUTION
-#-------------------------------------------------------------------------------
-
 # DESCRIPTION:
-#   Runs a given control script of a GitPack project with a timeout. In case of
-#   a timeout or a script fail, it prints an error report.
+#   Runs a given control script of a GitPack project. In case the script fails,
+#   it prints and logs an error report.
 # PARAMETERS:
 #   $1 - control script path
 run_control_script() {
-    timeout "$SCRIPT_TIMEOUT" "$1" && # run the script with a predefined timeout
-    return # return early if the script returned successfully and not timed out
+    "$1" && return # run the script and return early if it exited successfully
 
-    timeout_status="$?" # store the failed exit status of the timeout
-    # exit status of the SIGCHLD signal indicates a timeout
-    if [ "$timeout_status" -eq "$SIGCHLD_EXIT_STATUS" ]; then
-        echof "$(basename "$1") script timed out"
-    else # otherwise, the script execution failed with the returned exit status
-        echof "$(basename "$1") script execution failed with $timeout_status"
-    fi
+    script_status="$?" # store the exit status of the failed script
+    echof "$(basename "$1") script execution failed with $script_status"
     return 1 # indicate error but do not propagate the exit status further
-}
-
-# DESCRIPTION:
-#   Runs a given script with a given timeout. Returns a SIGCHLD exit status when
-#   timed out. Otherwise, returns the exit status of a given script execution.
-# PARAMETERS:
-#   $1 - duration in seconds
-#   $2 - script path
-timeout() { (
-    # in case of a termination signal, kill both processes and exit
-    trap 'timeout_term_action "$sleep_pid" "$script_pid"' HUP INT QUIT TERM &&
-    # once a child process terminates, both processes must be killed
-    trap 'kill "$sleep_pid" "$script_pid" 2>/dev/null' CHLD || return
-
-    ./"$2" & script_pid="$!" # run the given script and store its process ID
-    sleep "$1" & sleep_pid="$!" # run the timer and store its process ID
-    wait "$script_pid" # wait for the script to terminate (or get killed)
-) }
-
-# DESCRIPTION:
-#   This function is expected to handle all termination signals that can be sent
-#   to timeout during its execution. It kills both sleep and script processes.
-# PARAMETERS:
-#   $1 - sleep process ID
-#   $2 - script process ID
-timeout_term_action() {
-    status="$?" # get exit status of the signal
-    kill "$1" "$2" 2>/dev/null # kill both timeout processes
-    exit "$status" # exit timeout
 }
 
 #-------------------------------------------------------------------------------
