Let CI fail again

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -23,7 +23,6 @@ main() {
     check_sw_deps &&
     init_constants &&
     init_strings &&
-    echo "$test" &&
     init_core_config &&
     init_config &&
     store_command "$0 $*" &&
@@ -391,6 +390,7 @@ list() (
 #   Cleans the GitPack cache and log performing checks for unintended removal.
 clean() (
     # log clean operation, also creates a log file if it does not exist
+    echo 'fictional fail' >&2 &&
     log "$COMMAND_CLEAN" "$CACHE_DIR"/ &&
 
     # clean log shortening it to a defined number of last lines
