Offline mode (#3)
* Move fail reports and returns to the same lines

* Add support for offline mode in refresh_repo()

* Add support for offline mode

* Add a report when project not available offline

* Accelerate CI tests using offline mode

* Add offline mode info to GUIDE.md

[skip ci]

* Rename illegal option to invalid option

* Use the current local commit in CI tests

* Add file checks after clean to CI tests

* Add some echo indicators for CI tests

* Remove echo indicators for CI tests

* Add report state categories to CI tests

* Remove unnecessary command substitutions in CI

* Disable git --depth option for Linux CI

* Incorporate Git --depth option to the whole CI

* Fix .travis.yml syntax

* Print another variables in CI...

* Fix printing the diagnostic variables

* Stop printing diagnostic messages in CI

* Set the default Git depth to 1 in CI again

* Remove general Git --depth from CI

* Add general Git --depth to CI

* Add note about bug during fetching commit in CI

* Add custom clone solution due to Travis CI bug

* Prepare to move away from Travis CI

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -32,13 +32,12 @@ main() {
 check_sw_deps() {
     # a list of required software
     sw_deps='command echo [ cd test pwd rm id mkdir touch grep git uname read cp
-             head cut true basename find rmdir tr date tail kill sort'
+             head cut true basename find rmdir tr date tail kill sort getopts'
 
     # check if any piece of software is missing
     for sw_dep in $sw_deps; do
         if ! command -v "$sw_dep" > /dev/null; then
-            echo "missing $sw_dep software" >&2
-            return 1
+            echo "missing $sw_dep software" >&2; return 1
         fi
     done
 }
@@ -115,13 +114,16 @@ init_constants() {
 #   not be changed later. Constants must be already initialized.
 init_strings() {
     HELP_MESSAGE="USAGE:
-  gitpack ACTION URL[=VERSION]...
+  gitpack ACTION [OPTION...] URL[=VERSION]...
   gitpack COMMAND
 
 ACTION:
   $ACTION_INSTALL    install/update projects
   $ACTION_UNINSTALL  uninstall projects
   $ACTION_STATUS     get status of projects
+
+OPTION:
+  -o  offline mode
 
 COMMAND:
   list   list installed projects
@@ -166,28 +168,44 @@ process_args() {
         help) echo "$HELP_MESSAGE"; return ;;
         about) echo "$ABOUT_MESSAGE"; return ;;
         '') echo 'no argument provided' >&2; return 1 ;;
-        *) echo "unrecognized argument $1" >&2; return 1 ;;
+        *) echo "invalid argument $1" >&2; return 1 ;;
     esac &&
 
     backup_database # if success, back up the GitPack database
 }
 
 # DESCRIPTION:
-#   Processes a given action over all given repository references.
+#   Processes a given action and its arguments.
 # PARAMETERS:
 #   $1 - action
-#   $@ - references
+#   $@ - action arguments
 process_action_args() {
-    if [ "$#" -eq 1 ]; then # check if there is any reference argument
-        echo 'no URL provided' >&2
-        return 1
-    fi
-
     init_runtime && # initialize runtime
     action="$1" && # use the given action
-    shift && # shift arguments to references
+    shift && # shift to action arguments
+
+    process_action_opts "$@" && # action options (sets the OPTIND variable)
+    shift "$((OPTIND - 1))" && # shift to reference arguments
+    if [ "$#" -eq 0 ]; then # check if there is any reference argument
+        echof 'no URL provided'; return 1
+    fi &&
+
     for ref in "$@"; do # process each reference individually with common action
         process_action "$action" "$ref" || return
+    done
+}
+
+# DESCRIPTION:
+#   Processes given arguments as action options. It sets the OPTIND variable
+#   holding the position of the following argument.
+# PARAMETERS:
+#   $@ - action arguments
+process_action_opts() {
+    while getopts :o opt; do # for each option argument
+        case "$opt" in
+            o)  OFFLINE_MODE=true ;;
+            \?) echof "invalid option -$OPTARG"; return 1 ;;
+        esac
     done
 }
 
@@ -201,8 +219,8 @@ backup_database() {
 #-------------------------------------------------------------------------------
 # DYNAMIC INITIALIZATION
 #-------------------------------------------------------------------------------
-# All constants of this section can be read in other code. All global variables
-# of this section can be accessed in other code.
+# All constants of this section can be read in other code. All global and
+# environment variables of this section can be accessed in other code.
 #-------------------------------------------------------------------------------
 
 # DESCRIPTION:
@@ -210,6 +228,7 @@ backup_database() {
 #   GitPack's environment, logging and file structure will be prepared.
 init_runtime() {
     init_global_vars &&
+    init_environment_vars &&
     init_paths &&
     init_logging && # logging starts from here
     init_traps &&
@@ -217,7 +236,7 @@ init_runtime() {
 }
 
 # DESCRIPTION:
-#   Initializes global variables. If there is a global variable, it must be
+#   Initializes all global variables. If there is a global variable, it must be
 #   stated here even though its value is going to be overwritten.
 init_global_vars() {
     id_out="$(id -u)" && # check if running as root, not a global variable
@@ -231,6 +250,12 @@ init_global_vars() {
 
     state= && # the state of the processed project
     dep_depth=0 # current dependency depth
+}
+
+# DESCRIPTION:
+#   Initializes all environment variables. They can be read in called scripts.
+init_environment_vars() {
+    export OFFLINE_MODE=false # GitPack offline mode
 }
 
 # DESCRIPTION:
@@ -289,8 +314,7 @@ init_database() {
 
     # check access to GitPack status file
     if [ ! -r "$STATUS_PATH" ] || [ ! -w "$STATUS_PATH" ]; then
-        echof 'cannot access status file'
-        return 1
+        echof 'cannot access status file'; return 1
     fi
 }
 
@@ -365,8 +389,7 @@ clean() {
 
     # clean Git cache
     if ! remove_dir "$CACHE_DIR"; then # in case of fail
-        echof 'failed to remove cache directory'
-        return 1
+        echof 'failed to remove cache directory'; return 1
     fi
 }
 
@@ -456,8 +479,7 @@ check_url() {
     url_regex='^[[:alnum:]_][[:alnum:]_\.-]*(/[[:alnum:]_][[:alnum:]_\.-]*){2}$'
 
     if ! echo "$1" | grep -qE "$url_regex"; then
-        echof 'unsupported URL delivered'
-        return 1
+        echof 'unsupported URL delivered'; return 1
     fi
 }
 
@@ -483,14 +505,18 @@ get_dep_prefix() {
 refresh_repo() { (
     repo_dir="$(url_to_path "$1")" && # get the repository directory path
     log "$LOGTYPE_REFRESH" "$1" "$repo_dir"/ &&
-    mkdir -p "$repo_dir"/ &&
-    cd "$repo_dir"/ &&
 
-    if [ ! -d .git/ ]; then # if the directory does not contain a Git directory
-        # clone Git repository, it may ask the user for a password
-        git clone -q --no-checkout https://"$1".git ./
-    else
+    if [ "$OFFLINE_MODE" = true ]; then # offline
+        if [ ! -d "$repo_dir"/ ]; then # fail if local repository does not exist
+            echof 'project is not downloaded'; return 1
+        fi
+    elif [ -d "$repo_dir"/ ]; then # refresh
+        cd "$repo_dir"/ &&
         git fetch -q origin # fetch remote updates
+    else # clone
+        mkdir -p "$repo_dir"/ && cd "$repo_dir"/ && # create directory
+        # create local repository by cloning, it may ask the user for a password
+        git clone -q --no-checkout https://"$1".git ./
     fi
 ) }
 
@@ -549,8 +575,7 @@ get_repo_hash() { (
         # print a given version if it is a valid Git commit object reference
         if ! git rev-parse --verify -q origin/"$2"'^{commit}' && # remote branch
            ! git rev-parse --verify -q "$2"'^{commit}'; then # tag or commit
-            echof "version $2 does not exist"
-            return 1
+            echof "version $2 does not exist"; return 1
         fi
     # get latest tag of the default branch (if any tag exists)
     elif tag="$(git describe --tags --abbrev=0 origin/master 2>/dev/null)"; then
@@ -646,8 +671,7 @@ next_dep_depth() {
 
     # check whether the new dependency depth value is valid
     if [ "$dep_depth" -gt "$MAX_DEP_DEPTH" ]; then
-        echof 'maximum dependency depth reached'
-        return 1
+        echof 'maximum dependency depth reached'; return 1
     fi
 }
 
@@ -843,8 +867,7 @@ for_each_route() { (
             eval "$2" "$route" || return
         done
     else # if the map file does not exist, fails
-        echof 'missing map file'
-        return 1
+        echof 'missing map file'; return 1
     fi
 ) }
 
