Add support for script timeout

diff --git a/src/gitpack b/src/gitpack
--- a/src/gitpack
+++ b/src/gitpack
@@ -36,8 +36,9 @@ main() {
 #   Checks whether all software dependencies are satisfied.
 check_deps() {
     # a list of required software
-    sw_list='command echo [ cd test pwd rm id mkdir touch dirname grep git ls '\
-'uname read cp head cut true basename find rmdir tr date tail mv'
+    sw_list='command echo [ cd test pwd rm id mkdir touch dirname grep git ls
+             uname read cp head cut true basename find rmdir tr date tail mv
+             kill sleep wait'
 
     # check if any piece of software is missing
     for sw in $sw_list; do
@@ -141,10 +142,9 @@ https://github.com/dominiksalvet/gitpack'
 # PARAMETERS:
 #   $@ - GitPack arguments
 init_configuration() {
-    # current GitPack command
-    COMMAND="$0 $*"
-    # clean configuration
+    COMMAND="$0 $*" # the complete current GitPack command
     LOG_LINES_KEPT=1000 # when shortening the log file, keep those last lines
+    SCRIPT_TIMEOUT=3600 # timeout in seconds used when calling custom scripts
 }
 
 #-------------------------------------------------------------------------------
@@ -704,7 +704,7 @@ install() { (
 
     if [ -x "$install_dir"/precp ]; then # before files copy
         log "$LOGTYPE_PRECP" "$1" "$2" "$install_method" &&
-        call_script "$install_dir"/precp
+        run_with_timeout "$install_dir"/precp "$SCRIPT_TIMEOUT"
     fi &&
 
     # copy all files by defined routes
@@ -713,7 +713,7 @@ install() { (
 
     if [ -x "$install_dir"/postcp ]; then # after files copy
         log "$LOGTYPE_POSTCP" "$1" "$2" "$install_method" &&
-        call_script "$install_dir"/postcp
+        run_with_timeout "$install_dir"/postcp "$SCRIPT_TIMEOUT"
     fi
 ) }
 
@@ -729,7 +729,7 @@ uninstall() { (
 
     if [ -x "$install_dir"/prerm ]; then # before files removal
         log "$LOGTYPE_PRERM" "$1" "$2" "$install_method" &&
-        call_script "$install_dir"/prerm
+        run_with_timeout "$install_dir"/prerm "$SCRIPT_TIMEOUT"
     fi &&
 
     # remove all files by defined routes
@@ -738,7 +738,7 @@ uninstall() { (
 
     if [ -x "$install_dir"/postrm ]; then # after files removal
         log "$LOGTYPE_POSTRM" "$1" "$2" "$install_method" &&
-        call_script "$install_dir"/postrm
+        run_with_timeout "$install_dir"/postrm "$SCRIPT_TIMEOUT"
     fi
 ) }
 
@@ -763,16 +763,28 @@ install_method_to_path() {
 }
 
 # DESCRIPTION:
-#   Calls a given custom script and prints an error if failed.
+#   Runs a given script with a given timeout. Prints an error if failed.
 # PARAMETERS:
 #   $1 - script path
-call_script() {
-    ./"$1" || {
-        script_status="$?"
+#   $2 - timeout in seconds
+run_with_timeout() { (
+    # once a child process terminates, the other gets killed by the trap
+    trap 'kill "$sleep_pid" 2>/dev/null || kill "$script_pid"' CHLD || return
+    ./"$1" & script_pid="$!" # run the given script and store its process ID
+    sleep "$2" & sleep_pid="$!" # run the timer and store its process ID
+    wait "$script_pid" && # wait for the script process to terminate
+    return # return early if wait (i.e., the script) was successful
+
+    script_status="$?" # catch wait exit status
+    trap - CHLD || return # reset SIGCHLD signal handler to default value
+    if [ "$script_status" -gt 128 ]; then # only SIGCHLD signal considered
+        echo "$(basename "$1") script timed out" >&2
+        return 1
+    else # script execution failed
         echo "$(basename "$1") script failed" >&2
         return "$script_status"
-    }
-}
+    fi
+) }
 
 #-------------------------------------------------------------------------------
 # COPY AND REMOVE FILES
